"""Market Model: deterministic structure, zone and phase primitives.

Strategy-agnostic feature extraction: WHAT price is doing (structure),
WHERE it is (zones), and WHAT STAGE the move is in (phase). Every
timeframe runs this identical pipeline.
"""

from forex_platform.market_model.contracts import (
    BreakType,
    MarketPhase,
    MarketState,
    MarketZone,
    StructureBreak,
    SwingPoint,
    SwingScope,
    SwingType,
    TimeframeState,
    ZoneScope,
    ZoneType,
)
from forex_platform.market_model.phases import (
    MarketPhaseClassifier,
    PhaseAssessment,
    classify_phase,
)
from forex_platform.market_model.structure import (
    detect_internal_swings,
    detect_structure_breaks,
    detect_swings,
    get_trend_direction,
    is_trend_invalidated,
    mark_protected_weak_swings,
    split_external_internal,
)
from forex_platform.market_model.zones import (
    FVGDirection,
    FairValueGap,
    LiquidityKind,
    LiquidityLevel,
    LiquidityLevelType,
    LiquidityPool,
    LiquiditySweep,
    OBDirection,
    OrderBlock,
    detect_fair_value_gaps,
    detect_liquidity_pools,
    detect_liquidity_sweeps,
    detect_order_blocks,
    extract_session_levels,
    fvgs_to_zones,
    latest_levels,
    levels_to_zones,
    liquidity_pools_to_zones,
    order_blocks_to_zones,
)

__all__ = [
    "BreakType",
    "FairValueGap",
    "FVGDirection",
    "LiquidityKind",
    "LiquidityLevel",
    "LiquidityLevelType",
    "LiquidityPool",
    "LiquiditySweep",
    "MarketPhase",
    "MarketPhaseClassifier",
    "MarketState",
    "MarketZone",
    "OBDirection",
    "OrderBlock",
    "PhaseAssessment",
    "StructureBreak",
    "SwingPoint",
    "SwingScope",
    "SwingType",
    "TimeframeState",
    "ZoneScope",
    "ZoneType",
    "classify_phase",
    "detect_fair_value_gaps",
    "detect_internal_swings",
    "detect_liquidity_pools",
    "detect_liquidity_sweeps",
    "detect_order_blocks",
    "detect_structure_breaks",
    "detect_swings",
    "extract_session_levels",
    "fvgs_to_zones",
    "get_trend_direction",
    "is_trend_invalidated",
    "latest_levels",
    "levels_to_zones",
    "liquidity_pools_to_zones",
    "mark_protected_weak_swings",
    "order_blocks_to_zones",
    "split_external_internal",
]
